# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CTMC restricted moments of labeled substitution counts
#' 
#' Computes the CTMC restricted moment matrices of labeled substitution counts 
#' for all orders less than or equal to the user-specified maximum order of 
#' interest.
#' 
#' The zeroth-order restricted moment matrix is defined to be the transition 
#' probability matrix.
#' 
#' @param t A nonnegative numeric scalar representing the CTMC time interval 
#'   length.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param L An indicator matrix that labels the substitutions of interest.
#' @param max_order An integer specifying the maximum moment order of interest.
#'   
#' @return A three-dimensional array that stores the restricted moment 
#'   matrices, where the third dimension indexes the different moment orders. 
#'   Specifically, if \code{outp} denotes the output array, then \code{outp[, ,
#'   k]} represents the restricted moment matrix of order \code{k - 1} for all 
#'   integers \code{k} between \code{1} and \code{max_order + 1}.
#'   
#' @references Van Loan C (1978) \dQuote{Computing Integrals Involving the 
#'   Matrix Exponential}, \emph{IEEE Transactions on Automatic Control}, 
#'   23(3):395-404.
#'   
#'   Minin VN and Suchard MA (2008) \dQuote{Counting labeled transitions in 
#'   continuous-time Markov models of evolution}, \emph{Journal of Mathematical
#'   Biology}, 56(3):391-412.
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{ctmc.reward.moments}}, 
#'   \code{\link{phylo.nsubs.moments}}
#'   
#' @export
ctmc.nsubs.moments <- function(t, subst_mod, L, max_order) {
    .Call(`_phylomd_ctmc_nsubs_moments`, t, subst_mod, L, max_order)
}

#' CTMC restricted moments of total rewards
#' 
#' Computes the CTMC restricted moment matrices of total rewards for all orders
#' less than or equal to the user-specified maximum order of interest.
#' 
#' The zeroth-order restricted moment matrix is defined to be the transition 
#' probability matrix.
#' 
#' @param t A nonnegative numeric scalar representing the CTMC time interval 
#'   length.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param w A numeric vector that defines the reward per unit time (reward 
#'   rate) for each CTMC state.
#' @param max_order An integer specifying the maximum moment order of interest.
#'   
#' @return A three-dimensional array that stores the restricted moment 
#'   matrices, where the third dimension indexes the different moment orders. 
#'   Specifically, if \code{outp} denotes the output array, then \code{outp[, ,
#'   k]} represents the restricted moment matrix of order \code{k - 1} for all 
#'   integers \code{k} between \code{1} and \code{max_order + 1}.
#'   
#' @references Van Loan C (1978) \dQuote{Computing Integrals Involving the 
#'   Matrix Exponential}, \emph{IEEE Transactions on Automatic Control}, 
#'   23(3):395-404.
#'   
#'   Minin VN and Suchard MA (2008) \dQuote{Fast, Accurate and Simulation-Free 
#'   Stochastic Mapping}, \emph{Philosophical Transactions of the Royal Society
#'   B: Biological Sciences}, 363(1512):3985-3995.
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{ctmc.nsubs.moments}}, 
#'   \code{\link{phylo.reward.moments}}
#'   
#' @export
ctmc.reward.moments <- function(t, subst_mod, w, max_order) {
    .Call(`_phylomd_ctmc_reward_moments`, t, subst_mod, w, max_order)
}

#' CTMC transition probability derivatives with respect to rate matrix 
#' parameters
#' 
#' Computes the CTMC transition probability derivative matrices with respect to
#' a given rate matrix parameter for all orders less than or equal to the 
#' user-specified maximum order of interest.
#' 
#' The zeroth-order transition probability derivative matrix is defined to be 
#' the transition probability matrix.
#' 
#' @param t A nonnegative numeric scalar representing the CTMC time interval 
#'   length.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param param_name The rate matrix parameter name of interest.
#' @param max_order An integer specifying the maximum derivative order of 
#'   interest.
#'   
#' @return A three-dimensional array that stores the transition probability 
#'   derivative matrices, where the third dimension indexes the different 
#'   derivative orders.  Specifically, if \code{outp} denotes the output array,
#'   then \code{outp[, , k]} represents the transition probability derivative 
#'   matrix of order \code{k - 1} for all integers \code{k} between \code{1} 
#'   and \code{max_order + 1}.
#'   
#' @references Van Loan C (1978) \dQuote{Computing Integrals Involving the 
#'   Matrix Exponential}, \emph{IEEE Transactions on Automatic Control}, 
#'   23(3):395-404.
#'   
#'   Kenney T and Gu H (2012) \dQuote{Hessian Calculation for Phylogenetic 
#'   Likelihood based on the Pruning Algorithm and its Applications}, 
#'   \emph{Statistical Applications in Genetics and Molecular Biology}, 11(4).
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{ctmc.t.derivatives}}, \code{\link{phylo.Q.derivatives}}
#'   
#' @export
ctmc.Q.derivatives <- function(t, subst_mod, param_name, max_order) {
    .Call(`_phylomd_ctmc_Q_derivatives`, t, subst_mod, param_name, max_order)
}

#' CTMC transition probability derivatives with respect to time interval length
#' 
#' Computes the CTMC transition probability derivative matrices with respect to
#' the time interval length for all orders less than or equal to the 
#' user-specified maximum order of interest.
#' 
#' The zeroth-order transition probability derivative matrix is defined to be 
#' the transition probability matrix.
#' 
#' @param t A nonnegative numeric scalar representing the CTMC time interval 
#'   length.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param max_order An integer specifying the maximum derivative order of 
#'   interest.
#'   
#' @return A three-dimensional array that stores the transition probability 
#'   derivative matrices, where the third dimension indexes the different 
#'   derivative orders.  Specifically, if \code{outp} denotes the output array,
#'   then \code{outp[, , k]} represents the transition probability derivative 
#'   matrix of order \code{k - 1} for all integers \code{k} between \code{1} 
#'   and \code{max_order + 1}.
#'   
#' @references Kenney T and Gu H (2012) \dQuote{Hessian Calculation for 
#'   Phylogenetic Likelihood based on the Pruning Algorithm and its 
#'   Applications}, \emph{Statistical Applications in Genetics and Molecular 
#'   Biology}, 11(4).
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{ctmc.Q.derivatives}}, \code{\link{phylo.t.derivatives}}
#'   
#' @export
ctmc.t.derivatives <- function(t, subst_mod, max_order) {
    .Call(`_phylomd_ctmc_t_derivatives`, t, subst_mod, max_order)
}

#' Phylogenetic stochastic mapping moments of labeled substitution counts
#' 
#' Computes the phylogenetic stochastic mapping moments of labeled substitution
#' counts for all orders less than or equal to the user-specified maximum order
#' of interest.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' The zeroth-order stochastic mapping moment is defined to be the phylogenetic
#' likelihood.
#' 
#' If an observed tip state is invalid, then it is treated as an ambiguous 
#' character state.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param L An indicator matrix that labels the substitutions of interest.
#' @param edge_sets A list of integer vectors that defines the edge sets over 
#'   which the moments are calculated.
#' @param max_order An integer specifying the maximum moment order of interest.
#' @param tip_states A character vector of observed tip states.
#'   
#' @return A named numeric vector that holds the computed stochastic mapping 
#'   moments.  Each element name is formed by concatenating strings of the form
#'   \code{"(E):O"} with \code{"--"} separators, where \code{E} denotes an edge
#'   set index, \code{O} represents the exponent order associated with the 
#'   additive mapping summary defined over the \code{E}th edge set, and 
#'   \code{"--"} symbolizes the product operator between two mapping summaries.
#'   However, the empty string (\code{""}) is the element name of the 
#'   zeroth-order stochastic mapping moment.
#'   
#' @references Minin VN and Suchard MA (2008) \dQuote{Fast, Accurate and 
#'   Simulation-Free Stochastic Mapping}, \emph{Philosophical Transactions of 
#'   the Royal Society B: Biological Sciences}, 363(1512):3985-3995.
#'   
#'   Dhar A and Minin VN (2017) \dQuote{Calculating Higher-Order Moments of 
#'   Phylogenetic Stochastic Mapping Summaries in Linear Time}, \emph{Journal 
#'   of Computational Biology}, 24(5):377-399.
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{phylo.reward.moments}}, 
#'   \code{\link{ctmc.nsubs.moments}}
#'   
#' @export
phylo.nsubs.moments <- function(tree, subst_mod, L, edge_sets, max_order, tip_states) {
    .Call(`_phylomd_phylo_nsubs_moments`, tree, subst_mod, L, edge_sets, max_order, tip_states)
}

#' Phylogenetic stochastic mapping moments of total rewards
#' 
#' Computes the phylogenetic stochastic mapping moments of total rewards for 
#' all orders less than or equal to the user-specified maximum order of 
#' interest.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' The zeroth-order stochastic mapping moment is defined to be the phylogenetic
#' likelihood.
#' 
#' If an observed tip state is invalid, then it is treated as an ambiguous 
#' character state.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param w A numeric vector that defines the reward per unit time (reward 
#'   rate) for each CTMC state.
#' @param edge_sets A list of integer vectors that defines the edge sets over 
#'   which the moments are calculated.
#' @param max_order An integer specifying the maximum moment order of interest.
#' @param tip_states A character vector of observed tip states.
#'   
#' @return A named numeric vector that holds the computed stochastic mapping 
#'   moments.  Each element name is formed by concatenating strings of the form
#'   \code{"(E):O"} with \code{"--"} separators, where \code{E} denotes an edge
#'   set index, \code{O} represents the exponent order associated with the 
#'   additive mapping summary defined over the \code{E}th edge set, and 
#'   \code{"--"} symbolizes the product operator between two mapping summaries.
#'   However, the empty string (\code{""}) is the element name of the 
#'   zeroth-order stochastic mapping moment.
#'   
#' @references Minin VN and Suchard MA (2008) \dQuote{Fast, Accurate and 
#'   Simulation-Free Stochastic Mapping}, \emph{Philosophical Transactions of 
#'   the Royal Society B: Biological Sciences}, 363(1512):3985-3995.
#'   
#'   Dhar A and Minin VN (2017) \dQuote{Calculating Higher-Order Moments of 
#'   Phylogenetic Stochastic Mapping Summaries in Linear Time}, \emph{Journal 
#'   of Computational Biology}, 24(5):377-399.
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{phylo.nsubs.moments}}, 
#'   \code{\link{ctmc.reward.moments}}
#'   
#' @export
phylo.reward.moments <- function(tree, subst_mod, w, edge_sets, max_order, tip_states) {
    .Call(`_phylomd_phylo_reward_moments`, tree, subst_mod, w, edge_sets, max_order, tip_states)
}

#' Phylogenetic likelihood derivatives with respect to rate matrix parameters
#' 
#' Computes the phylogenetic likelihood derivatives with respect to a given 
#' rate matrix parameter for all orders less than or equal to the 
#' user-specified maximum order of interest.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' The zeroth-order likelihood derivative is defined to be the phylogenetic 
#' likelihood.
#' 
#' If an observed tip state is invalid, then it is treated as an ambiguous 
#' character state.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param param_name The rate matrix parameter name of interest.
#' @param max_order An integer specifying the maximum derivative order of 
#'   interest.
#' @param tip_states A character vector of observed tip states.
#'   
#' @return A named numeric vector that holds the computed likelihood 
#'   derivatives.  Each element name is a string of the form \code{"(1):O"}, 
#'   where \code{O} represents the derivative order of the corresponding 
#'   element.  However, the empty string (\code{""}) is the element name of the
#'   zeroth-order likelihood derivative.
#'   
#' @references Kenney T and Gu H (2012) \dQuote{Hessian Calculation for 
#'   Phylogenetic Likelihood based on the Pruning Algorithm and its 
#'   Applications}, \emph{Statistical Applications in Genetics and Molecular 
#'   Biology}, 11(4).
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{phylo.t.derivatives}}, \code{\link{ctmc.Q.derivatives}}
#'   
#' @export
phylo.Q.derivatives <- function(tree, subst_mod, param_name, max_order, tip_states) {
    .Call(`_phylomd_phylo_Q_derivatives`, tree, subst_mod, param_name, max_order, tip_states)
}

#' Phylogenetic likelihood derivatives with respect to branch lengths
#' 
#' Computes the phylogenetic likelihood derivatives with respect to the branch 
#' lengths for all orders less than or equal to the user-specified maximum 
#' order of interest.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' The zeroth-order likelihood derivative is defined to be the phylogenetic 
#' likelihood.
#' 
#' If an observed tip state is invalid, then it is treated as an ambiguous 
#' character state.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param max_order An integer specifying the maximum derivative order of 
#'   interest.
#' @param tip_states A character vector of observed tip states.
#'   
#' @return A named numeric vector that holds the computed likelihood 
#'   derivatives.  Each element name is formed by concatenating strings of the 
#'   form \code{"(E):O"} with \code{"--"} separators, where \code{E} denotes an
#'   edge index, \code{O} represents the derivative order associated with the 
#'   edge index \code{E}, and \code{"--"} symbolizes the partial 
#'   differentiation operator with respect to two branch lengths.  However, the
#'   empty string (\code{""}) is the element name of the zeroth-order 
#'   likelihood derivative.
#'   
#' @references Kenney T and Gu H (2012) \dQuote{Hessian Calculation for 
#'   Phylogenetic Likelihood based on the Pruning Algorithm and its 
#'   Applications}, \emph{Statistical Applications in Genetics and Molecular 
#'   Biology}, 11(4).
#'   
#'   OUR PAPER!!
#'   
#' @seealso \code{\link{phylo.Q.derivatives}}, \code{\link{ctmc.t.derivatives}}
#'   
#' @export
phylo.t.derivatives <- function(tree, subst_mod, max_order, tip_states) {
    .Call(`_phylomd_phylo_t_derivatives`, tree, subst_mod, max_order, tip_states)
}

#' CTMC path simulation
#' 
#' Simulates a CTMC sample path.
#' 
#' @param t A nonnegative numeric scalar representing the CTMC time interval 
#'   length.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param init_state A string that specifies the initial state of the CTMC.
#'   
#' @return A data frame with two columns.  The \code{"time"} column holds the 
#'   times at which each of the simulated CTMC states is entered and the 
#'   \code{"state"} column stores the corresponding CTMC states.
#'   
#' @references Nielsen R (2002) \dQuote{Mapping Mutations on Phylogenies}, 
#'   \emph{Systematic Biology}, 51(5):729-739.
#'   
#' @seealso \code{\link{asr.sim}}, \code{\link{smap.sim}}, 
#'   \code{\link{tips.sim}}
#'   
#' @export
ctmc.sim <- function(t, subst_mod, init_state) {
    .Call(`_phylomd_ctmc_sim`, t, subst_mod, init_state)
}

#' Phylogenetic ancestral state reconstruction
#' 
#' Samples ancestral states at the internal nodes of a phylogeny conditional on
#' observed tip states.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' If an observed tip state is invalid, then it is treated as an ambiguous 
#' character state.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param tip_states A character vector of observed tip states.
#'   
#' @return A character vector that holds the sampled ancestral states and 
#'   observed tip states.
#'   
#' @references Nielsen R (2002) \dQuote{Mapping Mutations on Phylogenies}, 
#'   \emph{Systematic Biology}, 51(5):729-739.
#'   
#' @seealso \code{\link{smap.sim}}, \code{\link{tips.sim}}, 
#'   \code{\link{ctmc.sim}}
#'   
#' @export
asr.sim <- function(tree, subst_mod, tip_states) {
    .Call(`_phylomd_asr_sim`, tree, subst_mod, tip_states)
}

#' Phylogenetic stochastic mapping simulation
#' 
#' Samples a stochastic mapping on a phylogeny conditional on observed tip 
#' states.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' If an observed tip state is invalid, then it is treated as an ambiguous 
#' character state.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#' @param tip_states A character vector of observed tip states.
#'   
#' @return A list that stores the simulated CTMC trajectory at each edge.
#'   
#' @references Nielsen R (2002) \dQuote{Mapping Mutations on Phylogenies}, 
#'   \emph{Systematic Biology}, 51(5):729-739.
#'   
#' @seealso \code{\link{asr.sim}}, \code{\link{tips.sim}}, 
#'   \code{\link{ctmc.sim}}
#'   
#' @export
smap.sim <- function(tree, subst_mod, tip_states) {
    .Call(`_phylomd_smap_sim`, tree, subst_mod, tip_states)
}

#' Phylogenetic tip state simulation
#' 
#' Simulates the tip states of a phylogeny.
#' 
#' More information on S3 objects of class \code{"phylo"} is found at 
#' \url{http://ape-package.ird.fr/misc/FormatTreeR_24Oct2012.pdf}.
#' 
#' @param tree An S3 object of class \code{"phylo"}.
#' @param subst_mod An S3 object of class \code{"substitution.model"}.
#'   
#' @return A character vector of simulated tip states.
#'   
#' @seealso \code{\link{asr.sim}}, \code{\link{smap.sim}}, 
#'   \code{\link{ctmc.sim}}
#'   
#' @export
tips.sim <- function(tree, subst_mod) {
    .Call(`_phylomd_tips_sim`, tree, subst_mod)
}

#' The Jukes-Cantor (JC69) substitution model
#'
#' Creates a Jukes-Cantor (JC69) substitution model object.
#'
#' @param mu A nonnegative numeric scalar representing the overall substitution
#'   rate.
#' @param scale A boolean indicating whether to scale the time dimension.  If
#'   \code{TRUE}, then time is specified in terms of the expected number of
#'   CTMC substitutions per site.
#'
#' @return A list (S3 object of class \code{"substitution.model"}) with the
#'   following named entries:
#'   \describe{
#'     \item{\code{states}}{The vector of DNA states.}
#'     \item{\code{Q}}{The JC69 rate matrix.}
#'     \item{\code{pi}}{The JC69 stationary distribution.}
#'     \item{\code{d_mu}}{The JC69 rate matrix derivative with respect to
#'       \code{mu}.}
#'   }
#'
#' @references Jukes TH and Cantor CR (1969) \dQuote{Evolution of Protein
#'   Molecules}, \emph{Mammalian Protein Metabolism}, (3):21-132.
#'
#' @seealso \code{\link{K80}}, \code{\link{F81}}, \code{\link{HKY85}},
#'   \code{\link{GTR}}
#'
#' @export
JC69 <- function(mu, scale = FALSE) {
    .Call(`_phylomd_JC69`, mu, scale)
}

#' The Kimura 2-parameter (K80) substitution model
#'
#' Creates a Kimura 2-parameter (K80) substitution model object.
#'
#' @param alpha A nonnegative numeric scalar representing the substitution rate
#'   of DNA transitions (\eqn{A <=> G} and \eqn{C <=> T}).
#' @param beta A nonnegative numeric scalar representing the substitution rate
#'   of DNA transversions (\eqn{A <=> C}, \eqn{A <=> T}, \eqn{C <=> G}, and
#'   \eqn{G <=> T}).
#' @param scale A boolean indicating whether to scale the time dimension.  If
#'   \code{TRUE}, then time is specified in terms of the expected number of
#'   CTMC substitutions per site.
#'
#' @return A list (S3 object of class \code{"substitution.model"}) with the
#'   following named entries:
#'   \describe{
#'     \item{\code{states}}{The vector of DNA states.}
#'     \item{\code{Q}}{The K80 rate matrix.}
#'     \item{\code{pi}}{The K80 stationary distribution.}
#'     \item{\code{d_alpha}}{The K80 rate matrix derivative with respect to
#'       \code{alpha}.}
#'     \item{\code{d_beta}}{The K80 rate matrix derivative with respect to
#'       \code{beta}.}
#'   }
#'
#' @references Kimura M (1980) \dQuote{A Simple Method for Estimating
#'   Evolutionary Rates of Base Substitutions Through Comparative Studies of
#'   Nucleotide Sequences}, \emph{Journal of Molecular Evolution},
#'   16(2):111-120.
#'
#' @seealso \code{\link{JC69}}, \code{\link{F81}}, \code{\link{HKY85}},
#'   \code{\link{GTR}}
#'
#' @export
K80 <- function(alpha, beta, scale = FALSE) {
    .Call(`_phylomd_K80`, alpha, beta, scale)
}

#' The Felsenstein (F81) substitution model
#'
#' Creates a Felsenstein (F81) substitution model object.
#'
#' @param mu A nonnegative numeric scalar representing the overall substitution
#'   rate.
#' @param pi A numeric vector defining the F81 stationary distribution.
#' @param scale A boolean indicating whether to scale the time dimension.  If
#'   \code{TRUE}, then time is specified in terms of the expected number of
#'   CTMC substitutions per site.
#'
#' @return A list (S3 object of class \code{"substitution.model"}) with the
#'   following named entries:
#'   \describe{
#'     \item{\code{states}}{The vector of DNA states.}
#'     \item{\code{Q}}{The F81 rate matrix.}
#'     \item{\code{pi}}{The F81 stationary distribution.}
#'     \item{\code{d_mu}}{The F81 rate matrix derivative with respect to
#'       \code{mu}.}
#'   }
#'
#' @references Felsenstein J (1981) \dQuote{Evolutionary Trees from DNA
#'   Sequences: A Maximum Likelihood Approach}, \emph{Journal of Molecular
#'   Evolution}, 17(6):368-376.
#'
#' @seealso \code{\link{JC69}}, \code{\link{K80}}, \code{\link{HKY85}},
#'   \code{\link{GTR}}
#'
#' @export
F81 <- function(mu, pi, scale = FALSE) {
    .Call(`_phylomd_F81`, mu, pi, scale)
}

#' The Hasegawa-Kishino-Yano (HKY85) substitution model
#'
#' Creates a Hasegawa-Kishino-Yano (HKY85) substitution model object.
#'
#' @param alpha A nonnegative numeric scalar representing the substitution rate
#'   of DNA transitions (\eqn{A <=> G} and \eqn{C <=> T}).
#' @param beta A nonnegative numeric scalar representing the substitution rate
#'   of DNA transversions (\eqn{A <=> C}, \eqn{A <=> T}, \eqn{C <=> G}, and
#'   \eqn{G <=> T}).
#' @param pi A numeric vector defining the HKY85 stationary distribution.
#' @param scale A boolean indicating whether to scale the time dimension.  If
#'   \code{TRUE}, then time is specified in terms of the expected number of
#'   CTMC substitutions per site.
#'
#' @return A list (S3 object of class \code{"substitution.model"}) with the
#'   following named entries:
#'   \describe{
#'     \item{\code{states}}{The vector of DNA states.}
#'     \item{\code{Q}}{The HKY85 rate matrix.}
#'     \item{\code{pi}}{The HKY85 stationary distribution.}
#'     \item{\code{d_alpha}}{The HKY85 rate matrix derivative with respect to
#'       \code{alpha}.}
#'     \item{\code{d_beta}}{The HKY85 rate matrix derivative with respect to
#'       \code{beta}.}
#'   }
#'
#' @references Hasegawa M, Kishino H, and Yano TA (1985) \dQuote{Dating of the
#'   Human-Ape Splitting by a Molecular Clock of Mitochondrial DNA}, \emph{
#'   Journal of Molecular Evolution}, 22(2):160-174.
#'
#' @seealso \code{\link{JC69}}, \code{\link{K80}}, \code{\link{F81}},
#'   \code{\link{GTR}}
#'
#' @export
HKY85 <- function(alpha, beta, pi, scale = FALSE) {
    .Call(`_phylomd_HKY85`, alpha, beta, pi, scale)
}

#' The general time-reversible (GTR) substitution model
#'
#' Creates a general time-reversible (GTR) substitution model object.
#'
#' @param rAC,rAG,rAT,rCG,rCT,rGT Nonnegative numeric scalars representing the
#'   \eqn{A <=> C}, \eqn{A <=> G}, \eqn{A <=> T}, \eqn{C <=> G}, \eqn{C <=> T},
#'   and \eqn{G <=> T} substitution rates, respectively.
#' @param pi A numeric vector defining the GTR stationary distribution.
#' @param scale A boolean indicating whether to scale the time dimension.  If
#'   \code{TRUE}, then time is specified in terms of the expected number of
#'   CTMC substitutions per site.
#'
#' @return A list (S3 object of class \code{"substitution.model"}) with the
#'   following named entries:
#'   \describe{
#'     \item{\code{states}}{The vector of DNA states.}
#'     \item{\code{Q}}{The GTR rate matrix.}
#'     \item{\code{pi}}{The GTR stationary distribution.}
#'     \item{\code{d_rAC}}{The GTR rate matrix derivative with respect to
#'       \code{rAC}.}
#'     \item{\code{d_rAG}}{The GTR rate matrix derivative with respect to
#'       \code{rAG}.}
#'     \item{\code{d_rAT}}{The GTR rate matrix derivative with respect to
#'       \code{rAT}.}
#'     \item{\code{d_rCG}}{The GTR rate matrix derivative with respect to
#'       \code{rCG}.}
#'     \item{\code{d_rCT}}{The GTR rate matrix derivative with respect to
#'       \code{rCT}.}
#'     \item{\code{d_rGT}}{The GTR rate matrix derivative with respect to
#'       \code{rGT}.}
#'   }
#'
#' @references Tavare S (1986) \dQuote{Some Probabilistic and Statistical
#'   Problems in the Analysis of DNA Sequences}, \emph{Lectures on Mathematics
#'   in the Life Sciences}, 17(2):57-86.
#'
#' @seealso \code{\link{JC69}}, \code{\link{K80}}, \code{\link{F81}},
#'   \code{\link{HKY85}}
#'
#' @export
GTR <- function(rAC, rAG, rAT, rCG, rCT, rGT, pi, scale = FALSE) {
    .Call(`_phylomd_GTR`, rAC, rAG, rAT, rCG, rCT, rGT, pi, scale)
}

